services:
  - type: web
    name: subtitle-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: uploads
      mountPath: /tmp/uploads
      sizeGB: 1
